# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

SETUP_DIR = 'C:\\Users\\lsfan\\PycharmProjects\\SYSU_LUNG'

a = Analysis(['main.py',
              'canvas.py',
              'common_import.py',
              'ui_MainWindow.py',
              'datatypes/__init__.py',
              'datatypes/annotations.py',
              'datatypes/dicom_tree.py',
              'datatypes/label_struct.py',
              'utils/__init__.py',
              'utils/dicom.py',
              'utils/file.py',
              'utils/qt.py',
              'widgets/__init__.py',
              'widgets/annotations_list_widget.py',
              'widgets/database_widget.py',
              'widgets/label_edit_widget.py',
              'widgets/series_list_widget.py',
              'widgets/wlww_widget.py',
              'widgets/zoom_widget.py',
              ],
             pathex=['C:\\Users\\lsfan\\PycharmProjects\\SYSU_LUNG'],
             binaries=[],
             datas=[(SETUP_DIR+'\\icons',SETUP_DIR+'\\build\\icons')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='app',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='app')
