# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelEditWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabelEditWidget(object):
    def setupUi(self, LabelEditWidget):
        LabelEditWidget.setObjectName("LabelEditWidget")
        LabelEditWidget.resize(603, 417)
        self.gridLayout = QtWidgets.QGridLayout(LabelEditWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.solidity_label = QtWidgets.QLabel(LabelEditWidget)
        self.solidity_label.setObjectName("solidity_label")
        self.gridLayout.addWidget(self.solidity_label, 1, 0, 1, 1)
        self.malignancy_label = QtWidgets.QLabel(LabelEditWidget)
        self.malignancy_label.setObjectName("malignancy_label")
        self.gridLayout.addWidget(self.malignancy_label, 0, 0, 1, 1)
        self.benign_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.benign_button.setObjectName("benign_button")
        self.buttonGroup = QtWidgets.QButtonGroup(LabelEditWidget)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.benign_button)
        self.gridLayout.addWidget(self.benign_button, 0, 1, 1, 1)
        self.malignant_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.malignant_button.setObjectName("malignant_button")
        self.buttonGroup.addButton(self.malignant_button)
        self.gridLayout.addWidget(self.malignant_button, 0, 2, 1, 1)
        self.malignancy_unknown_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.malignancy_unknown_button.setObjectName("malignancy_unknown_button")
        self.buttonGroup.addButton(self.malignancy_unknown_button)
        self.gridLayout.addWidget(self.malignancy_unknown_button, 0, 3, 1, 1)
        self.segmentation_comgbobox = QtWidgets.QComboBox(LabelEditWidget)
        self.segmentation_comgbobox.setObjectName("segmentation_comgbobox")
        self.segmentation_comgbobox.addItem("")
        self.gridLayout.addWidget(self.segmentation_comgbobox, 2, 3, 1, 1)
        self.add_sign_button = QtWidgets.QPushButton(LabelEditWidget)
        self.add_sign_button.setObjectName("add_sign_button")
        self.gridLayout.addWidget(self.add_sign_button, 3, 1, 1, 1)
        self.lobulation_label = QtWidgets.QLabel(LabelEditWidget)
        self.lobulation_label.setObjectName("lobulation_label")
        self.gridLayout.addWidget(self.lobulation_label, 2, 0, 1, 1)
        self.comment_label = QtWidgets.QLabel(LabelEditWidget)
        self.comment_label.setObjectName("comment_label")
        self.gridLayout.addWidget(self.comment_label, 4, 0, 1, 1)
        self.lobulation_combobox = QtWidgets.QComboBox(LabelEditWidget)
        self.lobulation_combobox.setObjectName("lobulation_combobox")
        self.lobulation_combobox.addItem("")
        self.lobulation_combobox.addItem("")
        self.lobulation_combobox.addItem("")
        self.lobulation_combobox.addItem("")
        self.lobulation_combobox.addItem("")
        self.lobulation_combobox.addItem("")
        self.gridLayout.addWidget(self.lobulation_combobox, 2, 1, 1, 1)
        self.comment_edit = QtWidgets.QTextEdit(LabelEditWidget)
        self.comment_edit.setTabletTracking(True)
        self.comment_edit.setTabChangesFocus(True)
        self.comment_edit.setObjectName("comment_edit")
        self.gridLayout.addWidget(self.comment_edit, 4, 1, 1, 3)
        self.solidity_unknown_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.solidity_unknown_button.setObjectName("solidity_unknown_button")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(LabelEditWidget)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.solidity_unknown_button)
        self.gridLayout.addWidget(self.solidity_unknown_button, 1, 3, 1, 1)
        self.solid_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.solid_button.setObjectName("solid_button")
        self.buttonGroup_2.addButton(self.solid_button)
        self.gridLayout.addWidget(self.solid_button, 1, 1, 1, 1)
        self.segmentation_label = QtWidgets.QLabel(LabelEditWidget)
        self.segmentation_label.setObjectName("segmentation_label")
        self.gridLayout.addWidget(self.segmentation_label, 2, 2, 1, 1)
        self.sign_label = QtWidgets.QLabel(LabelEditWidget)
        self.sign_label.setObjectName("sign_label")
        self.gridLayout.addWidget(self.sign_label, 3, 0, 1, 1)
        self.ground_glass_button = QtWidgets.QRadioButton(LabelEditWidget)
        self.ground_glass_button.setObjectName("ground_glass_button")
        self.buttonGroup_2.addButton(self.ground_glass_button)
        self.gridLayout.addWidget(self.ground_glass_button, 1, 2, 1, 1)
        self.apply_button = QtWidgets.QPushButton(LabelEditWidget)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout.addWidget(self.apply_button, 5, 0, 1, 1)
        self.reset_button = QtWidgets.QPushButton(LabelEditWidget)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout.addWidget(self.reset_button, 5, 3, 1, 1)
        self.sign_combobox = QtWidgets.QComboBox(LabelEditWidget)
        self.sign_combobox.setObjectName("sign_combobox")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.sign_combobox.addItem("")
        self.gridLayout.addWidget(self.sign_combobox, 3, 2, 1, 2)

        self.retranslateUi(LabelEditWidget)
        QtCore.QMetaObject.connectSlotsByName(LabelEditWidget)
        LabelEditWidget.setTabOrder(self.malignancy_unknown_button, self.malignant_button)
        LabelEditWidget.setTabOrder(self.malignant_button, self.benign_button)
        LabelEditWidget.setTabOrder(self.benign_button, self.solidity_unknown_button)
        LabelEditWidget.setTabOrder(self.solidity_unknown_button, self.ground_glass_button)
        LabelEditWidget.setTabOrder(self.ground_glass_button, self.solid_button)
        LabelEditWidget.setTabOrder(self.solid_button, self.lobulation_combobox)
        LabelEditWidget.setTabOrder(self.lobulation_combobox, self.segmentation_comgbobox)
        LabelEditWidget.setTabOrder(self.segmentation_comgbobox, self.add_sign_button)
        LabelEditWidget.setTabOrder(self.add_sign_button, self.sign_combobox)
        LabelEditWidget.setTabOrder(self.sign_combobox, self.comment_edit)
        LabelEditWidget.setTabOrder(self.comment_edit, self.apply_button)
        LabelEditWidget.setTabOrder(self.apply_button, self.reset_button)

    def retranslateUi(self, LabelEditWidget):
        _translate = QtCore.QCoreApplication.translate
        LabelEditWidget.setWindowTitle(_translate("LabelEditWidget", "标签"))
        self.solidity_label.setText(_translate("LabelEditWidget", "实性"))
        self.malignancy_label.setText(_translate("LabelEditWidget", "良恶"))
        self.benign_button.setText(_translate("LabelEditWidget", "良性"))
        self.malignant_button.setText(_translate("LabelEditWidget", "恶性"))
        self.malignancy_unknown_button.setText(_translate("LabelEditWidget", "？"))
        self.segmentation_comgbobox.setItemText(0, _translate("LabelEditWidget", "？"))
        self.add_sign_button.setText(_translate("LabelEditWidget", "+"))
        self.lobulation_label.setText(_translate("LabelEditWidget", "分叶"))
        self.comment_label.setText(_translate("LabelEditWidget", "备注"))
        self.lobulation_combobox.setItemText(0, _translate("LabelEditWidget", "？"))
        self.lobulation_combobox.setItemText(1, _translate("LabelEditWidget", "左肺上叶"))
        self.lobulation_combobox.setItemText(2, _translate("LabelEditWidget", "左肺下叶"))
        self.lobulation_combobox.setItemText(3, _translate("LabelEditWidget", "右肺上叶"))
        self.lobulation_combobox.setItemText(4, _translate("LabelEditWidget", "右肺中叶"))
        self.lobulation_combobox.setItemText(5, _translate("LabelEditWidget", "右肺下叶"))
        self.solidity_unknown_button.setText(_translate("LabelEditWidget", "？"))
        self.solid_button.setText(_translate("LabelEditWidget", "实性"))
        self.segmentation_label.setText(_translate("LabelEditWidget", "分段"))
        self.sign_label.setText(_translate("LabelEditWidget", "影像学征象"))
        self.ground_glass_button.setText(_translate("LabelEditWidget", "磨玻璃"))
        self.apply_button.setText(_translate("LabelEditWidget", "应用"))
        self.reset_button.setText(_translate("LabelEditWidget", "重置"))
        self.sign_combobox.setItemText(0, _translate("LabelEditWidget", "无"))
        self.sign_combobox.setItemText(1, _translate("LabelEditWidget", "分叶征"))
        self.sign_combobox.setItemText(2, _translate("LabelEditWidget", "毛刺征"))
        self.sign_combobox.setItemText(3, _translate("LabelEditWidget", "空泡征"))
        self.sign_combobox.setItemText(4, _translate("LabelEditWidget", "细支气管征"))
        self.sign_combobox.setItemText(5, _translate("LabelEditWidget", "空洞征"))
        self.sign_combobox.setItemText(6, _translate("LabelEditWidget", "血管集束征"))
        self.sign_combobox.setItemText(7, _translate("LabelEditWidget", "胸膜凹陷征"))
        self.sign_combobox.setItemText(8, _translate("LabelEditWidget", "结节内小支气管壁局部增厚"))
        self.sign_combobox.setItemText(9, _translate("LabelEditWidget", "管腔局部狭窄"))
        self.sign_combobox.setItemText(10, _translate("LabelEditWidget", "毛玻璃病灶内见实性成份"))

