# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.canvas_area = QtWidgets.QWidget(MainWindow)
        self.canvas_area.setObjectName("canvas_area")
        MainWindow.setCentralWidget(self.canvas_area)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDiagnose = QtWidgets.QMenu(self.menubar)
        self.menuDiagnose.setObjectName("menuDiagnose")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.annotation_list_dock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.annotation_list_dock.sizePolicy().hasHeightForWidth())
        self.annotation_list_dock.setSizePolicy(sizePolicy)
        self.annotation_list_dock.setObjectName("annotation_list_dock")
        self.placeholder2 = QtWidgets.QWidget()
        self.placeholder2.setObjectName("placeholder2")
        self.annotation_list_dock.setWidget(self.placeholder2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.annotation_list_dock)
        self.label_edit_dock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_edit_dock.sizePolicy().hasHeightForWidth())
        self.label_edit_dock.setSizePolicy(sizePolicy)
        self.label_edit_dock.setObjectName("label_edit_dock")
        self.placeholder3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeholder3.sizePolicy().hasHeightForWidth())
        self.placeholder3.setSizePolicy(sizePolicy)
        self.placeholder3.setObjectName("placeholder3")
        self.label_edit_dock.setWidget(self.placeholder3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.label_edit_dock)
        self.dataset_tree_dock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataset_tree_dock.sizePolicy().hasHeightForWidth())
        self.dataset_tree_dock.setSizePolicy(sizePolicy)
        self.dataset_tree_dock.setObjectName("dataset_tree_dock")
        self.placeholder5 = QtWidgets.QWidget()
        self.placeholder5.setObjectName("placeholder5")
        self.dataset_tree_dock.setWidget(self.placeholder5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dataset_tree_dock)
        self.series_list_dock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.series_list_dock.sizePolicy().hasHeightForWidth())
        self.series_list_dock.setSizePolicy(sizePolicy)
        self.series_list_dock.setObjectName("series_list_dock")
        self.placeholder6 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeholder6.sizePolicy().hasHeightForWidth())
        self.placeholder6.setSizePolicy(sizePolicy)
        self.placeholder6.setObjectName("placeholder6")
        self.series_list_dock.setWidget(self.placeholder6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.series_list_dock)
        self.open_file_action = QtWidgets.QAction(MainWindow)
        self.open_file_action.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/open_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file_action.setIcon(icon)
        self.open_file_action.setObjectName("open_file_action")
        self.open_dir_action = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_dir_action.setIcon(icon1)
        self.open_dir_action.setObjectName("open_dir_action")
        self.quit_action = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/quit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_action.setIcon(icon2)
        self.quit_action.setObjectName("quit_action")
        self.open_next_image_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_next_image_action.setIcon(icon3)
        self.open_next_image_action.setObjectName("open_next_image_action")
        self.open_prev_image_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/prev.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_prev_image_action.setIcon(icon4)
        self.open_prev_image_action.setObjectName("open_prev_image_action")
        self.save_file_action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_file_action.setIcon(icon5)
        self.save_file_action.setObjectName("save_file_action")
        self.saveas_file_action = QtWidgets.QAction(MainWindow)
        self.saveas_file_action.setIcon(icon5)
        self.saveas_file_action.setObjectName("saveas_file_action")
        self.delete_file_action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_file_action.setIcon(icon6)
        self.delete_file_action.setObjectName("delete_file_action")
        self.change_output_dir_action = QtWidgets.QAction(MainWindow)
        self.change_output_dir_action.setObjectName("change_output_dir_action")
        self.set_autosave_action = QtWidgets.QAction(MainWindow)
        self.set_autosave_action.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/unchecked.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap("icons/checked.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.set_autosave_action.setIcon(icon7)
        self.set_autosave_action.setObjectName("set_autosave_action")
        self.create_polygon_action = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/polygon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_polygon_action.setIcon(icon8)
        self.create_polygon_action.setObjectName("create_polygon_action")
        self.create_rectangle_action = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/rectangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_rectangle_action.setIcon(icon9)
        self.create_rectangle_action.setObjectName("create_rectangle_action")
        self.create_circle_action = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_circle_action.setIcon(icon10)
        self.create_circle_action.setObjectName("create_circle_action")
        self.create_polyline_action = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/polyline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_polyline_action.setIcon(icon11)
        self.create_polyline_action.setObjectName("create_polyline_action")
        self.create_line_action = QtWidgets.QAction(MainWindow)
        self.create_line_action.setObjectName("create_line_action")
        self.create_point_action = QtWidgets.QAction(MainWindow)
        self.create_point_action.setObjectName("create_point_action")
        self.edit_mode_action = QtWidgets.QAction(MainWindow)
        self.edit_mode_action.setIcon(icon7)
        self.edit_mode_action.setObjectName("edit_mode_action")
        self.canvas_undo_action = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.canvas_undo_action.setIcon(icon12)
        self.canvas_undo_action.setObjectName("canvas_undo_action")
        self.select_line_color_action = QtWidgets.QAction(MainWindow)
        self.select_line_color_action.setObjectName("select_line_color_action")
        self.select_fill_color_action = QtWidgets.QAction(MainWindow)
        self.select_fill_color_action.setObjectName("select_fill_color_action")
        self.set_keep_prev_action = QtWidgets.QAction(MainWindow)
        self.set_keep_prev_action.setCheckable(True)
        self.set_keep_prev_action.setObjectName("set_keep_prev_action")
        self.copy_annotation_action = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_annotation_action.setIcon(icon13)
        self.copy_annotation_action.setObjectName("copy_annotation_action")
        self.delete_annotataion_action = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_annotataion_action.setIcon(icon14)
        self.delete_annotataion_action.setObjectName("delete_annotataion_action")
        self.add_point_to_nearest_edge_action = QtWidgets.QAction(MainWindow)
        self.add_point_to_nearest_edge_action.setObjectName("add_point_to_nearest_edge_action")
        self.set_annotation_visibility_action = QtWidgets.QAction(MainWindow)
        self.set_annotation_visibility_action.setCheckable(True)
        self.set_annotation_visibility_action.setObjectName("set_annotation_visibility_action")
        self.zoom_in_action = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/zoom_in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in_action.setIcon(icon15)
        self.zoom_in_action.setObjectName("zoom_in_action")
        self.zoom_out_action = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/zoom_out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_action.setIcon(icon16)
        self.zoom_out_action.setObjectName("zoom_out_action")
        self.fit_window_action = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/fit_window.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fit_window_action.setIcon(icon17)
        self.fit_window_action.setObjectName("fit_window_action")
        self.fit_window_width_action = QtWidgets.QAction(MainWindow)
        self.fit_window_width_action.setObjectName("fit_window_width_action")
        self.edit_annotation_label_action = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/label.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_annotation_label_action.setIcon(icon18)
        self.edit_annotation_label_action.setObjectName("edit_annotation_label_action")
        self.edit_annotation_line_color_action = QtWidgets.QAction(MainWindow)
        self.edit_annotation_line_color_action.setObjectName("edit_annotation_line_color_action")
        self.set_fill_annotation_action = QtWidgets.QAction(MainWindow)
        self.set_fill_annotation_action.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/unchecked.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_fill_annotation_action.setIcon(icon19)
        self.set_fill_annotation_action.setObjectName("set_fill_annotation_action")
        self.edit_annotation_fill_color_action = QtWidgets.QAction(MainWindow)
        self.edit_annotation_fill_color_action.setObjectName("edit_annotation_fill_color_action")
        self.open_help_doc_action = QtWidgets.QAction(MainWindow)
        self.open_help_doc_action.setObjectName("open_help_doc_action")
        self.excute_lung_nodule_analysis_action = QtWidgets.QAction(MainWindow)
        self.excute_lung_nodule_analysis_action.setObjectName("excute_lung_nodule_analysis_action")
        self.label_edit_dock.raise_()
        self.annotation_list_dock.raise_()
        self.series_list_dock.raise_()
        self.dataset_tree_dock.raise_()
        self.menuFile.addAction(self.open_file_action)
        self.menuFile.addAction(self.open_dir_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.save_file_action)
        self.menuFile.addAction(self.saveas_file_action)
        self.menuFile.addAction(self.delete_file_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.open_prev_image_action)
        self.menuFile.addAction(self.open_next_image_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.change_output_dir_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.quit_action)
        self.menuEdit.addAction(self.create_polygon_action)
        self.menuEdit.addAction(self.create_rectangle_action)
        self.menuEdit.addAction(self.create_circle_action)
        self.menuEdit.addAction(self.create_polyline_action)
        self.menuEdit.addAction(self.create_line_action)
        self.menuEdit.addAction(self.create_point_action)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.select_line_color_action)
        self.menuEdit.addAction(self.select_fill_color_action)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.edit_mode_action)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.copy_annotation_action)
        self.menuEdit.addAction(self.delete_annotataion_action)
        self.menuEdit.addAction(self.add_point_to_nearest_edge_action)
        self.menuEdit.addAction(self.edit_annotation_label_action)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.canvas_undo_action)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.set_keep_prev_action)
        self.menuEdit.addAction(self.set_fill_annotation_action)
        self.menuEdit.addAction(self.set_autosave_action)
        self.menuEdit.addSeparator()
        self.menuView.addAction(self.zoom_in_action)
        self.menuView.addAction(self.zoom_out_action)
        self.menuView.addAction(self.fit_window_action)
        self.menuView.addAction(self.fit_window_width_action)
        self.menuView.addSeparator()
        self.menuView.addAction(self.set_annotation_visibility_action)
        self.menuHelp.addAction(self.open_help_doc_action)
        self.menuDiagnose.addAction(self.excute_lung_nodule_analysis_action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDiagnose.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.open_file_action)
        self.toolBar.addAction(self.open_dir_action)
        self.toolBar.addAction(self.open_next_image_action)
        self.toolBar.addAction(self.open_prev_image_action)
        self.toolBar.addAction(self.save_file_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.create_polygon_action)
        self.toolBar.addAction(self.create_rectangle_action)
        self.toolBar.addAction(self.copy_annotation_action)
        self.toolBar.addAction(self.delete_annotataion_action)
        self.toolBar.addAction(self.canvas_undo_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.zoom_in_action)
        self.toolBar.addAction(self.zoom_out_action)
        self.toolBar.addAction(self.fit_window_action)
        self.toolBar.addAction(self.fit_window_width_action)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SYSULUNG"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuEdit.setTitle(_translate("MainWindow", "标记(&A)"))
        self.menuView.setTitle(_translate("MainWindow", "视图(&V)"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menuDiagnose.setTitle(_translate("MainWindow", "诊断(&D)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.annotation_list_dock.setWindowTitle(_translate("MainWindow", "标记列表"))
        self.label_edit_dock.setWindowTitle(_translate("MainWindow", "标签编辑器"))
        self.dataset_tree_dock.setWindowTitle(_translate("MainWindow", "数据库"))
        self.series_list_dock.setWindowTitle(_translate("MainWindow", "当前序列"))
        self.open_file_action.setText(_translate("MainWindow", "打开文件"))
        self.open_file_action.setToolTip(_translate("MainWindow", "打开一个文件"))
        self.open_dir_action.setText(_translate("MainWindow", "打开文件夹"))
        self.open_dir_action.setToolTip(_translate("MainWindow", "选择文件夹，添加其中所有满足条件的文件"))
        self.open_dir_action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.quit_action.setText(_translate("MainWindow", "退出程序"))
        self.quit_action.setToolTip(_translate("MainWindow", "退出程序"))
        self.open_next_image_action.setText(_translate("MainWindow", "下一张"))
        self.open_next_image_action.setToolTip(_translate("MainWindow", "查看下一张图像，按下Ctrl+Shift进行标记保持"))
        self.open_next_image_action.setShortcut(_translate("MainWindow", "D"))
        self.open_prev_image_action.setText(_translate("MainWindow", "上一张"))
        self.open_prev_image_action.setToolTip(_translate("MainWindow", "查看上一张图像，按下Ctrl+Shift进行标记保持"))
        self.open_prev_image_action.setShortcut(_translate("MainWindow", "A"))
        self.save_file_action.setText(_translate("MainWindow", "保存"))
        self.save_file_action.setToolTip(_translate("MainWindow", "保存对当前图像的更改"))
        self.save_file_action.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.saveas_file_action.setText(_translate("MainWindow", "另存为"))
        self.saveas_file_action.setToolTip(_translate("MainWindow", "将当前图像以指定格式保存到指定位置"))
        self.delete_file_action.setText(_translate("MainWindow", "删除标记文件"))
        self.delete_file_action.setToolTip(_translate("MainWindow", "删除当前图像的标记文件"))
        self.change_output_dir_action.setText(_translate("MainWindow", "更改输出文件夹"))
        self.change_output_dir_action.setToolTip(_translate("MainWindow", "更改当前文件序列的标记输出文件夹"))
        self.set_autosave_action.setText(_translate("MainWindow", "自动保存"))
        self.set_autosave_action.setToolTip(_translate("MainWindow", "启用/禁用自动保存"))
        self.set_autosave_action.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.create_polygon_action.setText(_translate("MainWindow", "创建多边形标记"))
        self.create_polygon_action.setToolTip(_translate("MainWindow", "创建多边形标记"))
        self.create_polygon_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.create_rectangle_action.setText(_translate("MainWindow", "创建矩形标记"))
        self.create_rectangle_action.setToolTip(_translate("MainWindow", "创建矩形标记"))
        self.create_rectangle_action.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.create_circle_action.setText(_translate("MainWindow", "创建圆形标记"))
        self.create_circle_action.setToolTip(_translate("MainWindow", "创建圆形标记"))
        self.create_polyline_action.setText(_translate("MainWindow", "创建折线标记"))
        self.create_polyline_action.setToolTip(_translate("MainWindow", "创建折线标记"))
        self.create_line_action.setText(_translate("MainWindow", "创建线段标记"))
        self.create_line_action.setToolTip(_translate("MainWindow", "创建线段标记"))
        self.create_point_action.setText(_translate("MainWindow", "创建点标记"))
        self.create_point_action.setToolTip(_translate("MainWindow", "创建点标记"))
        self.edit_mode_action.setText(_translate("MainWindow", "进入编辑模式"))
        self.edit_mode_action.setToolTip(_translate("MainWindow", "进入编辑模式，对标记进行编辑和诊断"))
        self.edit_mode_action.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.canvas_undo_action.setText(_translate("MainWindow", "撤销"))
        self.canvas_undo_action.setToolTip(_translate("MainWindow", "撤销对标记的上一次操作"))
        self.canvas_undo_action.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.select_line_color_action.setText(_translate("MainWindow", "边框颜色"))
        self.select_line_color_action.setToolTip(_translate("MainWindow", "选择创建标记时边框的颜色"))
        self.select_fill_color_action.setText(_translate("MainWindow", "填充颜色"))
        self.select_fill_color_action.setToolTip(_translate("MainWindow", "选择创建标记时填充的颜色"))
        self.set_keep_prev_action.setText(_translate("MainWindow", "标记保持"))
        self.set_keep_prev_action.setToolTip(_translate("MainWindow", "启动/禁用标记保持，决定是否将当前图像标记复制到下一张打开的图像"))
        self.copy_annotation_action.setText(_translate("MainWindow", "复制标记"))
        self.copy_annotation_action.setToolTip(_translate("MainWindow", "在当前选中的标记旁创建一个拷贝"))
        self.delete_annotataion_action.setText(_translate("MainWindow", "删除标记"))
        self.delete_annotataion_action.setToolTip(_translate("MainWindow", "删除当前选中的标记"))
        self.add_point_to_nearest_edge_action.setText(_translate("MainWindow", "添加点到标记"))
        self.add_point_to_nearest_edge_action.setToolTip(_translate("MainWindow", "向距离指针最近的边增加一个点"))
        self.set_annotation_visibility_action.setText(_translate("MainWindow", "标记可见"))
        self.set_annotation_visibility_action.setToolTip(_translate("MainWindow", "显示/隐藏所有标记"))
        self.set_annotation_visibility_action.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.zoom_in_action.setText(_translate("MainWindow", "放大图像"))
        self.zoom_in_action.setToolTip(_translate("MainWindow", "将图像放大1.1倍"))
        self.zoom_out_action.setText(_translate("MainWindow", "缩小图像"))
        self.zoom_out_action.setToolTip(_translate("MainWindow", "将图像缩小为0.9倍"))
        self.fit_window_action.setText(_translate("MainWindow", "适合窗口"))
        self.fit_window_action.setToolTip(_translate("MainWindow", "将图像缩放到适合当前窗口"))
        self.fit_window_width_action.setText(_translate("MainWindow", "适合窗口宽度"))
        self.fit_window_width_action.setToolTip(_translate("MainWindow", "将图像缩放到适合窗口宽度"))
        self.edit_annotation_label_action.setText(_translate("MainWindow", "编辑标记标签"))
        self.edit_annotation_label_action.setToolTip(_translate("MainWindow", "编辑当前选中标记的标签"))
        self.edit_annotation_line_color_action.setText(_translate("MainWindow", "编辑边框颜色"))
        self.edit_annotation_line_color_action.setToolTip(_translate("MainWindow", "选择当前选中标记边框的颜色"))
        self.set_fill_annotation_action.setText(_translate("MainWindow", "标记填充"))
        self.set_fill_annotation_action.setToolTip(_translate("MainWindow", "启用/禁用对标记的填充"))
        self.edit_annotation_fill_color_action.setText(_translate("MainWindow", "编辑填充颜色"))
        self.edit_annotation_fill_color_action.setToolTip(_translate("MainWindow", "选择当前选中标记填充的颜色"))
        self.open_help_doc_action.setText(_translate("MainWindow", "打开帮助文档"))
        self.open_help_doc_action.setToolTip(_translate("MainWindow", "打开帮助文档"))
        self.excute_lung_nodule_analysis_action.setText(_translate("MainWindow", "完整肺结节分析"))
        self.excute_lung_nodule_analysis_action.setToolTip(_translate("MainWindow", "对当前序列进行肺结节检测，分类和特征提取"))

